categories:
  pronouns_single: [我, 你, 他, 她]
  pronouns_plural: [我们, 你们, 他们, 她们]
  pronouns: [pronouns_single, pronouns_plural]
  animals: [猫, 狗, 牛, 羊, 猪, 鸡, 鱼, 鸟]
  countries: [美国, 俄国, 中国, 日本, 法国, 英国]
  professions: [teacher, 医生, 记者]
  adjectives: [好, 小, 大, 美, 贵, 高, 高兴, 忙]
  relatives: [妈妈, 爸爸, 弟弟, 哥哥, 妹妹, 姐姐, 奶奶, 外婆, 女儿, 儿子, 朋友, 男朋友, 女朋友]
  nature: [山, 森林]
  drinks: [咖啡, 茶, 牛奶, 水]
  food: [猪肉, 牛肉, 羊肉, 鸡, 鱼, 土豆]
  subject_single: [pronouns_single, animals, relatives, professions]
  plural: [pronouns_plural, 父母, subject_plural]
  object_single: [animals, food, drinks]
  subject_object_verbs: [有, 没有, 要, 不要, 喜欢, 不喜欢]
  verbs: [有, 没有, 喝, 吃, 去, 爱, 要, 很, 喜欢]
  aux: [都, 和, 人, 不, 吗]

rules:
  teacher: [countries, 老师]
  subject_plural: [subject_single, 和, subject_single]

sentences:
  sentence_rule1: [subject_single, subject_object_verbs, object_single, 。]
  sentence_rule2: [subject_single, 喜欢吃, food, 。]
  sentence_rule3: [subject_single, 喜欢喝, drinks, 。]
  sentence_rule4: [subject_single, 很, adjectives, 。]
  sentence_rule5: [subject_single, 喜欢吃, food, 吗？]
  sentence_rule6: [subject_single, 喜欢喝, drinks, 吗？]
  sentence_rule7: [subject_single, 很, adjectives, 吗？]
  sentence_rule8: [plural,  都, 喜欢吃, food, 。]
  sentence_rule9: [plural,  都, 喜欢喝, drinks, 。]
  sentence_rule10: [plural,  都, 很, adjectives, 。]
  sentence_rule11: [plural,  都, 喜欢吃, food, 吗？]
  sentence_rule12: [plural,  都, 喜欢喝, drinks, 吗？]
  sentence_rule13: [plural,  都, 很, adjectives, 吗？]
  sentence_rule14: [plural,  都, 很, adjectives, 。]
  sentence_rule15: [plural,  都, 很, adjectives, 吗？]
